<build>

    <sourceDirectory>${project.basedir}</sourceDirectory>

    <resources>
        <resource>
            <directory>${project.basedir}</directory>
            <includes>
                <include>application.properties</include>
            </includes>
        </resource>
    </resources>

    <plugins>

        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>

            <configuration>
                <mainClass>com.memorylink.MemoryLinkApplication</mainClass>
            </configuration>

        </plugin>

    </plugins>

</build>
